-- ETL for fact_card_account
-- Sources: card_account, risk_score, card_product, reward_program, merchant
-- Generated by spark-pdm-generator

INSERT OVERWRITE TABLE fact_card_account
PARTITION (report_date)
SELECT
    card_account.account_id,
    card_account.report_date,
    card_account.product_id,
    card_account.customer_name,
    card_account.credit_limit,
    card_account.reward_program_id,
    risk_score.fico_score AS risk_score_fico_score,
    risk_score.behavioral_score AS risk_score_behavioral_score,
    card_product.product_name AS card_product_product_name,
    card_product.product_type AS card_product_product_type,
    card_product.annual_fee AS card_product_annual_fee,
    reward_program.program_id AS reward_program_program_id,
    reward_program.program_name AS reward_program_program_name,
    reward_program.points_multiplier AS reward_program_points_multiplier,
    merchant.merchant_id AS merchant_merchant_id,
    merchant.merchant_name AS merchant_merchant_name,
    merchant.mcc_code AS merchant_mcc_code
FROM card_account card_account
LEFT JOIN risk_score risk_score
    ON card_account.account_id = risk_score.account_id
LEFT JOIN card_product card_product
    ON card_account.product_id = card_product.product_id
LEFT JOIN reward_program reward_program
    ON card_account.reward_program_id = reward_program.program_id
LEFT JOIN merchant merchant
    ON card_account.account_id = merchant.merchant_id
