-- ETL for fact_balance_detail
-- Sources: balance_detail
-- Generated by spark-pdm-generator

INSERT OVERWRITE TABLE fact_balance_detail
PARTITION (report_date)
SELECT
    balance_detail.account_id,
    balance_detail.report_date,
    balance_detail.current_balance,
    balance_detail.statement_balance,
    balance_detail.minimum_payment_due,
    balance_detail.interest_accrued,
    balance_detail.payment_amount
FROM balance_detail balance_detail
