-- ETL for dim_risk_score
-- Sources: risk_score
-- Generated by spark-pdm-generator

INSERT OVERWRITE TABLE dim_risk_score
PARTITION (scoring_date)
SELECT
    risk_score.account_id,
    risk_score.scoring_date,
    risk_score.fico_score,
    risk_score.behavioral_score,
    risk_score.delinquency_bucket,
    risk_score.probability_of_default
FROM risk_score risk_score
