-- ETL for fact_card_account
-- Sources: card_account, card_product, reward_program
-- Generated by spark-pdm-generator

INSERT OVERWRITE TABLE fact_card_account
PARTITION (report_date)
SELECT
    card_account.account_id,
    card_account.report_date,
    card_account.product_id,
    card_account.customer_name,
    card_account.credit_limit,
    card_account.open_date,
    card_account.account_status,
    card_account.state_code,
    card_account.reward_program_id,
    card_product.product_name AS card_product_product_name,
    card_product.product_type AS card_product_product_type,
    card_product.annual_fee AS card_product_annual_fee,
    reward_program.program_id AS reward_program_program_id,
    reward_program.program_name AS reward_program_program_name,
    reward_program.points_multiplier AS reward_program_points_multiplier
FROM card_account card_account
LEFT JOIN card_product card_product
    ON card_account.product_id = card_product.product_id
LEFT JOIN reward_program reward_program
    ON card_account.reward_program_id = reward_program.program_id
