-- ETL for dim_merchant
-- Sources: merchant
-- Generated by spark-pdm-generator

INSERT OVERWRITE TABLE dim_merchant
SELECT
    merchant.merchant_id,
    merchant.merchant_name,
    merchant.mcc_code,
    merchant.merchant_state
FROM merchant merchant
