"""ETL for fact_account_transaction_agg
Sources: account_transaction_agg
Generated by spark-pdm-generator"""

from pyspark.sql import SparkSession
from pyspark.sql import functions as F


spark = SparkSession.builder.appName(
    "load_fact_account_transaction_agg"
).getOrCreate()

df_account_transaction_agg = spark.table("account_transaction_agg")

df_result = df_account_transaction_agg

df_result = df_result.select(
    F.col("account_id"),
    F.col("report_date"),
    F.col("total_spend"),
    F.col("transaction_count"),
    F.col("avg_ticket_size"),
    F.col("top_mcc_code")
)

df_result.write \
    .mode("overwrite") \
    .partitionBy("report_date") \
    .bucketBy(32, "account_id") \
    .sortBy("account_id", "top_mcc_code") \
    .option("compression", "zstd") \
    .format("parquet") \
    .saveAsTable("fact_account_transaction_agg")

spark.stop()