"""ETL for dim_merchant
Sources: merchant
Generated by spark-pdm-generator"""

from pyspark.sql import SparkSession
from pyspark.sql import functions as F


spark = SparkSession.builder.appName(
    "load_dim_merchant"
).getOrCreate()

df_merchant = spark.table("merchant")

df_result = df_merchant

df_result = df_result.select(
    F.col("merchant_id"),
    F.col("merchant_name"),
    F.col("mcc_code"),
    F.col("merchant_state")
)

df_result.write \
    .mode("overwrite") \
    .bucketBy(16, "merchant_id") \
    .sortBy("merchant_id") \
    .option("compression", "zstd") \
    .format("parquet") \
    .saveAsTable("dim_merchant")

spark.stop()