"""ETL for dim_collections_status
Sources: collections_status
Generated by spark-pdm-generator"""

from pyspark.sql import SparkSession
from pyspark.sql import functions as F


spark = SparkSession.builder.appName(
    "load_dim_collections_status"
).getOrCreate()

df_collections_status = spark.table("collections_status")

df_result = df_collections_status

df_result = df_result.select(
    F.col("account_id"),
    F.col("report_date"),
    F.col("collection_status"),
    F.col("promise_to_pay"),
    F.col("recovery_amount")
)

df_result.write \
    .mode("overwrite") \
    .partitionBy("report_date") \
    .bucketBy(16, "account_id") \
    .sortBy("account_id") \
    .option("compression", "zstd") \
    .format("parquet") \
    .saveAsTable("dim_collections_status")

spark.stop()