"""ETL builder: generates SQL and PySpark ETL scripts for physical table creation."""

from pathlib import Path

from spark_pdm_generator.models.logical import LogicalModel
from spark_pdm_generator.models.physical import PhysicalEntity, PhysicalModel


class ETLBuilder:
    """Builds ETL scripts for populating physical tables from source data."""

    def __init__(self, logical_model: LogicalModel) -> None:
        self.logical_model = logical_model

    def build_sql(
        self,
        entity: PhysicalEntity,
        output: PhysicalModel,
    ) -> str:
        """Generate SQL-based ETL for a physical entity.

        Produces an INSERT OVERWRITE ... SELECT that:
        1. Reads from source entities
        2. Joins as needed (for denormalized sources)
        3. Writes to the physical table with partitioning
        """
        attrs = output.get_attributes_for_entity(entity.physical_entity_name)
        sources = entity.source_entities

        if not sources:
            return (
                f"-- ETL for {entity.physical_entity_name}\n"
                f"-- WARNING: No source entities defined. Cannot generate ETL.\n"
            )

        # Build SELECT column list with lineage
        select_cols = []
        for attr in attrs:
            if attr.source_entity and attr.source_attribute:
                alias = attr.source_entity
                if attr.source_attribute != attr.attribute_name:
                    select_cols.append(
                        f"    {alias}.{attr.source_attribute} AS {attr.attribute_name}"
                    )
                else:
                    select_cols.append(f"    {alias}.{attr.source_attribute}")
            else:
                select_cols.append(f"    {attr.attribute_name}")

        select_sql = ",\n".join(select_cols)

        # Build FROM clause with joins
        if len(sources) <= 1:
            from_sql = f"FROM {sources[0]} {sources[0]}"
            join_sql = ""
        else:
            primary = sources[0]
            from_sql = f"FROM {primary} {primary}"
            join_parts = []
            for secondary in sources[1:]:
                join_cols = self._find_join_columns(output, primary, secondary)
                if join_cols:
                    on_clause = " AND ".join(
                        f"{primary}.{jk[0]} = {secondary}.{jk[1]}" for jk in join_cols
                    )
                else:
                    on_clause = "1 = 1 -- WARNING: join condition could not be determined"

                join_parts.append(
                    f"LEFT JOIN {secondary} {secondary}\n    ON {on_clause}"
                )
            join_sql = "\n".join(join_parts)

        # Build partition clause
        partition_sql = ""
        if entity.partition_columns:
            part_cols = ", ".join(entity.partition_columns)
            partition_sql = f"PARTITION ({part_cols})\n"

        # Assemble
        sql = (
            f"-- ETL for {entity.physical_entity_name}\n"
            f"-- Sources: {', '.join(sources)}\n"
            f"-- Generated by spark-pdm-generator\n\n"
            f"INSERT OVERWRITE TABLE {entity.physical_entity_name}\n"
            f"{partition_sql}"
            f"SELECT\n"
            f"{select_sql}\n"
            f"{from_sql}\n"
        )
        if join_sql:
            sql += f"{join_sql}\n"

        return sql

    def build_pyspark(
        self,
        entity: PhysicalEntity,
        output: PhysicalModel,
    ) -> str:
        """Generate PySpark DataFrame API ETL for a physical entity."""
        attrs = output.get_attributes_for_entity(entity.physical_entity_name)
        sources = entity.source_entities

        if not sources:
            return (
                f'# ETL for {entity.physical_entity_name}\n'
                f'# WARNING: No source entities defined. Cannot generate ETL.\n'
            )

        lines = [
            f'"""ETL for {entity.physical_entity_name}',
            f"Sources: {', '.join(sources)}",
            f'Generated by spark-pdm-generator"""',
            "",
            "from pyspark.sql import SparkSession",
            "from pyspark.sql import functions as F",
            "",
            "",
            'spark = SparkSession.builder.appName(',
            f'    "load_{entity.physical_entity_name}"',
            ").getOrCreate()",
            "",
        ]

        # Read source tables
        for source in sources:
            lines.append(f'df_{source} = spark.table("{source}")')
        lines.append("")

        # Build join chain
        if len(sources) > 1:
            primary = sources[0]
            lines.append(f"df_result = df_{primary}")
            for secondary in sources[1:]:
                join_cols = self._find_join_columns(output, primary, secondary)
                if join_cols:
                    conditions = " & ".join(
                        f'(df_{primary}["{jk[0]}"] == df_{secondary}["{jk[1]}"])'
                        for jk in join_cols
                    )
                    lines.append(
                        f"df_result = df_result.join(df_{secondary}, {conditions}, 'left')"
                    )
                else:
                    lines.append(f"# WARNING: join columns for {secondary} could not be determined")
                    lines.append(f"# df_result = df_result.join(df_{secondary}, [...], 'left')")
            lines.append("")
        else:
            lines.append(f"df_result = df_{sources[0]}")
            lines.append("")

        # Select and rename columns
        select_exprs = []
        for attr in attrs:
            if attr.source_entity and attr.source_attribute:
                if attr.source_attribute != attr.attribute_name:
                    select_exprs.append(
                        f'    F.col("{attr.source_attribute}").alias("{attr.attribute_name}")'
                    )
                else:
                    select_exprs.append(f'    F.col("{attr.source_attribute}")')
            else:
                select_exprs.append(f'    F.col("{attr.attribute_name}")')

        lines.append("df_result = df_result.select(")
        lines.append(",\n".join(select_exprs))
        lines.append(")")
        lines.append("")

        # Write with partitioning and bucketing
        write_chain = ['df_result.write']
        write_chain.append('    .mode("overwrite")')

        if entity.partition_columns:
            parts = ", ".join(f'"{c}"' for c in entity.partition_columns)
            write_chain.append(f"    .partitionBy({parts})")

        if entity.bucket_column and entity.bucket_count:
            sort_cols = ", ".join(
                f'"{sc.column_name}"' for sc in entity.sort_columns
            )
            write_chain.append(
                f'    .bucketBy({entity.bucket_count}, "{entity.bucket_column}")'
            )
            if sort_cols:
                write_chain.append(f"    .sortBy({sort_cols})")

        write_chain.append(f'    .option("compression", "{entity.compression_codec.lower()}")')
        write_chain.append('    .format("parquet")')
        write_chain.append(f'    .saveAsTable("{entity.physical_entity_name}")')

        lines.append(" \\\n".join(write_chain))
        lines.append("")
        lines.append("spark.stop()")

        return "\n".join(lines)

    def _find_join_columns(
        self, output: PhysicalModel, entity1: str, entity2: str
    ) -> list[tuple[str, str]]:
        """Find join columns between two source entities.

        Returns list of (entity1_col, entity2_col) tuples.
        Checks physical relationships first, then falls back to logical relationships.
        """
        # Check physical relationships
        for rel in output.physical_relationships:
            if (
                rel.parent_physical_entity == entity1
                and rel.child_physical_entity == entity2
            ) or (
                rel.parent_physical_entity == entity2
                and rel.child_physical_entity == entity1
            ):
                return [(c, c) for c in rel.join_columns]

        # Fall back to logical relationships (for absorbed/denormalized entities)
        for rel in self.logical_model.relationships:
            if rel.parent_entity == entity1 and rel.child_entity == entity2:
                return list(zip(rel.parent_key_columns, rel.child_key_columns))
            if rel.parent_entity == entity2 and rel.child_entity == entity1:
                return list(zip(rel.child_key_columns, rel.parent_key_columns))

        return []


def emit_etl_files(
    output: PhysicalModel, output_dir: Path, logical_model: LogicalModel
) -> None:
    """Write ETL files to the output directory."""
    builder = ETLBuilder(logical_model)

    # SQL ETL files
    sql_dir = output_dir / "etl" / "sql"
    sql_dir.mkdir(parents=True, exist_ok=True)

    for entity in output.physical_entities:
        sql = builder.build_sql(entity, output)
        filepath = sql_dir / f"load_{entity.physical_entity_name}.sql"
        filepath.write_text(sql, encoding="utf-8")

    # PySpark ETL files
    pyspark_dir = output_dir / "etl" / "pyspark"
    pyspark_dir.mkdir(parents=True, exist_ok=True)

    for entity in output.physical_entities:
        py = builder.build_pyspark(entity, output)
        filepath = pyspark_dir / f"load_{entity.physical_entity_name}.py"
        filepath.write_text(py, encoding="utf-8")
