-- ETL for dim_collections_status
-- Sources: collections_status
-- Generated by spark-pdm-generator

INSERT OVERWRITE TABLE dim_collections_status
PARTITION (report_date)
SELECT
    collections_status.account_id,
    collections_status.report_date,
    collections_status.collection_status,
    collections_status.promise_to_pay,
    collections_status.recovery_amount
FROM collections_status collections_status
