-- ETL for fact_account_transaction_agg
-- Sources: account_transaction_agg
-- Generated by spark-pdm-generator

INSERT OVERWRITE TABLE fact_account_transaction_agg
PARTITION (report_date)
SELECT
    account_transaction_agg.account_id,
    account_transaction_agg.report_date,
    account_transaction_agg.total_spend,
    account_transaction_agg.transaction_count,
    account_transaction_agg.avg_ticket_size,
    account_transaction_agg.top_mcc_code
FROM account_transaction_agg account_transaction_agg
