"""ETL for fact_balance_detail
Sources: balance_detail
Generated by spark-pdm-generator"""

from pyspark.sql import SparkSession
from pyspark.sql import functions as F


spark = SparkSession.builder.appName(
    "load_fact_balance_detail"
).getOrCreate()

df_balance_detail = spark.table("balance_detail")

df_result = df_balance_detail

df_result = df_result.select(
    F.col("account_id"),
    F.col("report_date"),
    F.col("current_balance"),
    F.col("statement_balance"),
    F.col("minimum_payment_due"),
    F.col("interest_accrued"),
    F.col("payment_amount")
)

df_result.write \
    .mode("overwrite") \
    .partitionBy("report_date") \
    .bucketBy(32, "account_id") \
    .sortBy("account_id") \
    .option("compression", "zstd") \
    .format("parquet") \
    .saveAsTable("fact_balance_detail")

spark.stop()