"""ETL for dim_risk_score
Sources: risk_score
Generated by spark-pdm-generator"""

from pyspark.sql import SparkSession
from pyspark.sql import functions as F


spark = SparkSession.builder.appName(
    "load_dim_risk_score"
).getOrCreate()

df_risk_score = spark.table("risk_score")

df_result = df_risk_score

df_result = df_result.select(
    F.col("account_id"),
    F.col("scoring_date"),
    F.col("fico_score"),
    F.col("behavioral_score"),
    F.col("delinquency_bucket"),
    F.col("probability_of_default")
)

df_result.write \
    .mode("overwrite") \
    .partitionBy("scoring_date") \
    .bucketBy(16, "account_id") \
    .sortBy("account_id") \
    .option("compression", "zstd") \
    .format("parquet") \
    .saveAsTable("dim_risk_score")

spark.stop()