"""ETL for fact_card_account
Sources: card_account, risk_score, card_product, reward_program, merchant
Generated by spark-pdm-generator"""

from pyspark.sql import SparkSession
from pyspark.sql import functions as F


spark = SparkSession.builder.appName(
    "load_fact_card_account"
).getOrCreate()

df_card_account = spark.table("card_account")
df_risk_score = spark.table("risk_score")
df_card_product = spark.table("card_product")
df_reward_program = spark.table("reward_program")
df_merchant = spark.table("merchant")

df_result = df_card_account
df_result = df_result.join(df_risk_score, (df_card_account["account_id"] == df_risk_score["account_id"]), 'left')
df_result = df_result.join(df_card_product, (df_card_account["product_id"] == df_card_product["product_id"]), 'left')
df_result = df_result.join(df_reward_program, (df_card_account["reward_program_id"] == df_reward_program["program_id"]), 'left')
df_result = df_result.join(df_merchant, (df_card_account["account_id"] == df_merchant["merchant_id"]), 'left')

df_result = df_result.select(
    F.col("account_id"),
    F.col("report_date"),
    F.col("product_id"),
    F.col("customer_name"),
    F.col("credit_limit"),
    F.col("reward_program_id"),
    F.col("fico_score").alias("risk_score_fico_score"),
    F.col("behavioral_score").alias("risk_score_behavioral_score"),
    F.col("product_name").alias("card_product_product_name"),
    F.col("product_type").alias("card_product_product_type"),
    F.col("annual_fee").alias("card_product_annual_fee"),
    F.col("program_id").alias("reward_program_program_id"),
    F.col("program_name").alias("reward_program_program_name"),
    F.col("points_multiplier").alias("reward_program_points_multiplier"),
    F.col("merchant_id").alias("merchant_merchant_id"),
    F.col("merchant_name").alias("merchant_merchant_name"),
    F.col("mcc_code").alias("merchant_mcc_code")
)

df_result.write \
    .mode("overwrite") \
    .partitionBy("report_date") \
    .bucketBy(2048, "account_id") \
    .sortBy("account_id", "product_id") \
    .option("compression", "zstd") \
    .format("parquet") \
    .saveAsTable("fact_card_account")

spark.stop()